<template>
  <iframe
    width="100%"
    height="200px"
    id="gmap_canvas"
    :src="`https://maps.google.com/maps?q=uzbekistan+navai+&t=&z=6&ie=UTF8&iwloc=&output=embed`"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
  >
  </iframe>
</template>